### ISSUE TITLE
Component activation life cycle

### ISSUE THREAD

**Issue by altus34** [PacktPublishing/Learning-Aurelia#2]
Hi,

In the book page 58.
Are you sure there is no an error:

canDeactivate(): Called at step #3 => not in step 2 ?
canActivate(): Called at step #2 => not in ste 3 ?

Thanks

**Comment by manuel-guilbault** [comment]
@altus34 you're absolutely right. Can you submit an errata at https://www.packtpub.com/books/content/errata?

**Comment by Inawire** [comment]
Would have been nice to have been in the errata by now. I went there first. Came here just on a hunch. That error for a new-bee had me questioning my understanding. Thanks altus34 for clearing it up.

PS: loving the book Manuel. So far it's helping me to put together all the individual blog posts and official documentation into context.

**Comment by manuel-guilbault** [comment]
@Inawire If you have a minute, can you [submit an errata](https://www.packtpub.com/books/content/errata) for this? If not, I'll submit it as soon as I get some time. Glad to know you like the book :)

**Comment by altus34** [comment]
DONE

**Comment by Inawire** [comment]
I just submitted it but then went to github and saw that altus34 had done one 5 days ago. Guess we are all busy (which is good).

Take care.

 
Regards

Ross MacLachlan



----- Original Message -----

**Comment by manuel-guilbault** [comment]
@altus34 many thanks!
@Inawire it's the thought that counts :)

**Comment by manuel-guilbault** [comment]
@prashantmishrapackt I think you can close this issue now that the errata is online

**Comment by prashantmishrapackt** [comment]
Thanks for helping us out @manuel-guilbault
