### ISSUE TITLE
Examples fail to work on macOS (and also will in Linux)

### ISSUE THREAD

**Issue by pbgc** [PacktPublishing/Learning-Aurelia#3]
In aurelia.json files are using windows-style path separators ( \ instead of / ) in some lines and if this file is not updated by hand, in every folder, the examples don't work.

For example in chapter-2/app
npm install
au run

gives:

unreachable code after return statement[Saber mais] vendor-bundle.js:3558:4
SyntaxError: import declarations may only appear at top level of a module main.js:1
TypeError: target is undefined[Saber mais] vendor-bundle.js:11300:1

Changing every \ to / on aurelia.json everything works.

relevant issues:
https://github.com/aurelia/cli/issues/332
https://github.com/aurelia/cli/issues/253

**Comment by MrBliz** [comment]
Exactly the same problem for me too, and your solution  worked

**Comment by manuel-guilbault** [comment]
@pbgc thanks for bringing that up!
I'll push the fix in the upcoming days.

**Comment by SimonHurst** [comment]
Interesting can't believe I didn't spot that myself. damn windows user haha ;p

**Comment by manuel-guilbault** [comment]
@SimonHurst did this fix the issues you had running the book's code samples?

**Comment by SimonHurst** [comment]
Yeah it did. Surprised it hadn't come up before though ;)

All the best
