### ISSUE TITLE
Helper function for E2E test doesn't seem to work well

### ISSUE THREAD

**Issue by pannpers** [PacktPublishing/Learning-Aurelia#6]
Hi, 

I'm at end-to-end tests section in Chapter 7 and facing a trouble about the following code snippet.

```
it('should display errors when clicking save and form is invalid', () => { 
  creationPo.setBirthDay('this is absolutely not a date'); 
  creationPo.phoneNumbers.clickAdd(); 
  creationPo.emailAddresses.clickAdd(); 
  creationPo.addresses.clickAdd(); 
  creationPo.socialProfiles.clickAdd(); 
     
  creationPo.clickSave(); 
 
  expect(creationPo.getTitle()).toEqual('New contact'); 
  expect(creationPo.getValidationErrors()).toEqual([ 
    'Birthday must be a valid date.',  
    'Address is required.',      
    'Number is required.',  
    'Street is required.',  
    'Postal Code is required.',  
    'City is required.',  
    'Country is required.',  
    'Username is required.' 
  ]); 
}); 
```

The helper function `clickAdd()` for only `phoneNumbers` doesn't seem to work well when I run the following command.
`au e2e`

I tried to comment out `creationPo.addresses.clickAdd();`, but a validation message `'Number is required.'`, which I expected to be displayed by the invalid phoneNumbers form, wasn't included in the result array of `getValidationErrors()`.
`clickAdd` function for phoneNumber was indeed called, but the form wasn't added for some reason.

I also tried a sample application for chapter 7, but the result is the same.
What's the cause of it and how should I modify the code?
Thank you.

**Comment by manuel-guilbault** [comment]
@panchan9 let me check it out over the weekend; I'll let you know what I find

**Comment by pannpers** [comment]
@manuel-guilbault Thank you for your kind help!!
Please let me know if you need more details.

**Comment by manuel-guilbault** [comment]
@panchan9 sorry for the long delay, I didn't have time before today to look at your issue.
On my end, the sample code in this repository works fine. Can you check it out and do a diff with your own code, in case you may have missed something?
