### ISSUE TITLE
Bootstrap form validation causing error

### ISSUE THREAD

**Issue by gaba2111** [PacktPublishing/Learning-Aurelia#7]
Hi,

I've got stuck at the end of Chapter 4 by adding `validation-renderer="bootstrap-form"` to contact-edition.html . It's causing an error when I'm trying to modify contact data:

`vendor-bundle.js:1395 Unhandled rejection TypeError: Cannot read property 'message' of undefined
    at BootstrapFormValidationRenderer.add (http://localhost:9000/scripts/app-bundle.js:637:34)
    at BootstrapFormValidationRenderer.render (http://localhost:9000/scripts/app-bundle.js:622:16)
    at ValidationController.processResultDelta (http://localhost:9000/scripts/vendor-bundle.js:6664:26)
    at http://localhost:9000/scripts/vendor-bundle.js:6550:23
From previous event:
    at ValidationController.validate (http://localhost:9000/scripts/vendor-bundle.js:6547:18)
    at ValidationController.validateBinding (http://localhost:9000/scripts/vendor-bundle.js:6685:18)
    at http://localhost:9000/scripts/vendor-bundle.js:6297:84
    at TaskQueue.flushMicroTaskQueue (http://localhost:9000/scripts/vendor-bundle.js:20677:16)
    at MutationObserver.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:20605:24)`

It happens only in case of contact-edition, it contact-photo it's working fine.

**Comment by manuel-guilbault** [comment]
Hi @gaba2111, can you check which version of `aurelia-validation` you installed? There have been some breaking changes between the development versions (0.14.0 was used for the book) and version 1.0.0, so if you used version 1.x.x, the `BootstrapFormValidationRenderer` class needs to change accordingly:

```js
export class BootstrapFormValidationRenderer {

  render(instruction) {
    for (let { result, elements } of instruction.unrender) {
      for (let element of elements) {
        this.remove(element, result);
      }
    }

    for (let { result, elements } of instruction.render) {
      for (let element of elements) {
        this.add(element, result);
      }
    }
  }

  add(element, result) {
    if (result.valid) {
      return;
    }

    const formGroup = element.closest('.form-group');
    if (!formGroup) {
      return;
    }
    
    formGroup.classList.add('has-error');

    const message = document.createElement('span');
    message.className = 'help-block validation-message';
    message.textContent = result.message;
    message.id = `bs-validation-message-${result.id}`;
    element.parentNode.insertBefore(message, element.nextSibling);
  }

  remove(element, result) {
    if (result.valid) {
      return;
    }

    const formGroup = element.closest('.form-group');
    if (!formGroup) {
      return;
    }

    const message = formGroup.querySelector(`#bs-validation-message-${result.id}`);
    if (message) {
      element.parentNode.removeChild(message);
      
      if (formGroup.querySelectorAll('.help-block.validation-message').length === 0) {    
        formGroup.classList.remove('has-error');
      }
    }
  }
}

```

Let me know how this goes.

**Comment by gaba2111** [comment]
Yeah, that solved my problem, thanks!

**Comment by manuel-guilbault** [comment]
@gaba2111 😄 

It would be awesome if you could [submit an errata to Packt](https://www.packtpub.com/books/info/packt/errata-submission-form-0) for this. Thanks in advance!
