### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by gaba2111** [PacktPublishing/Learning-Aurelia#8]
Hi, I wanted to deploy my app to see how does it work but I cannot do it. There is some problem with server.js in backend. I was trying to do it on heroku and it causes error H10. Do you have any idea what is wrong?

**Comment by techsachinkumar** [comment]
Hi gaba2111,

Could you provide more clarity on this issue?

Regards

**Comment by MurtazaTinwala** [comment]
Closing as no further classification.

Regards,
